### ISSUE TITLE
The "Rb99 AIM-120B" seems to have the same behavior (no tracking in TWS)

The AIM-120C-5 appears to work as expected in TWS.

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#49]
See track file

**Comment by DJTaz1975** [comment]
there seems to be an issue yes with 120b and tws.

I think its a range thing but need to test it more to confirm....

I launched 1 from 32nm and lofting it 20deg. and it went into space  120 000 ft +

a second problem seems to be since the first missile is not tracking second launch wil not go for the second locked target.
will test more to confirm.

**Comment by CIChesty** [comment]
On the more recent dev builds the AIM-120C-5 and C-7 seem to be affected now as well. I can't get any missiles to track in TWS unless fired within pitbull range.

In STT they will track as expected and even go pitbull and keep tracking if you break the lock. In TWS I haven't had any successful launches.

**Comment by currenthill** [comment]
The TWS tracking problem has been solved.
